<a href="https://colab.research.google.com/github/Chandhana-sanoj/exit_exam_ict/blob/main/Exit_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import os
import random

from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_excel("/content/partpdf_1782718798615_partpdf_1772778618075_partpdf_1763620814447_airbnb.xlsx")

In [25]:
df.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating,Host Since_dt
0,500,26 06 2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN,2008-06-26
1,500,26 06 2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0,2008-06-26
2,1039,25 07 2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0,2008-07-25
3,1783,12 08 2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0,2008-08-12
4,2078,15 08 2008,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0,2008-08-15

In [4]:
df.shape

(30475, 13)

In [5]:
df.columns

Index(['Host Id', 'Host Since', 'Name', 'Neighbourhood ', 'Property Type',
       'Review Scores Rating (bin)', 'Room Type', 'Zipcode', 'Beds',
       'Number of Records', 'Number Of Reviews', 'Price',
       'Review Scores Rating'],
      dtype='object')

##Task 1

In [6]:
df.dtypes

Host Id                                int64
Host Since                    datetime64[ns]
Name                                  object
Neighbourhood                         object
Property Type                         object
Review Scores Rating (bin)           float64
Room Type                             object
Zipcode                              float64
Beds                                 float64
Number of Records                      int64
Number Of Reviews                      int64
Price                                  int64
Review Scores Rating                 float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30475 entries, 0 to 30474
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30475 non-null  int64
 1   Host Since                  30475 non-null  datetime64[ns]
 2   Name                        30475 non-null  object
 3   Neighbourhood               30475 non-null  object
 4   Property Type               30472 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30475 non-null  object
 7   Zipcode                     30341 non-null  float64
 8   Beds                        30390 non-null  float64
 9   Number of Records           30475 non-null  int64
 10  Number Of Reviews           30475 non-null  int64
 11  Price                       30475 non-null  int64
 12  Review Scores Rating        22155 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(4)
memory usage: 3.0+ MB

In [29]:
# parse (use dayfirst=True if dates are day-month in your locale)
df['Host Since'] = pd.to_datetime(df['Host Since'], errors='coerce', dayfirst=True)

In [37]:
df['Host Since'] = pd.to_datetime(df['Host Since'], format='%d %m %Y', errors='coerce')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30475 entries, 0 to 30474
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30475 non-null  int64
 1   Host Since                  30475 non-null  datetime64[ns]
 2   Name                        30475 non-null  object
 3   Neighbourhood               30475 non-null  object
 4   Property Type               30472 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30475 non-null  object
 7   Zipcode                     30341 non-null  float64
 8   Beds                        30390 non-null  float64
 9   Number of Records           30475 non-null  int64
 10  Number Of Reviews           30475 non-null  int64
 11  Price                       30475 non-null  int64
 12  Review Scores Rating        22155 non-null  float64
 13  Host Since_dt               30475 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(4), int64(4), object(4)
memory usage: 3.3+ MB

In [40]:
#Host Experience
#experienced hosts likely learn and adapt to optimal pricing strategies for their listings, considering factors like seasonality, demand, and local events.
#This accumulated knowledge could allow them to set more competitive or higher prices compared to newer hosts who might be still experimenting.

In [39]:
df.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating,Host Since_dt
0,500,2008-06-26,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN,2008-06-26
1,500,2008-06-26,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0,2008-06-26
2,1039,2008-07-25,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0,2008-07-25
3,1783,2008-08-12,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0,2008-08-12
4,2078,2008-08-15,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0,2008-08-15

In [24]:
df.describe()

,Host Id,Review Scores Rating (bin),Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating,Host Since_dt
count,3.047500e+04,22155.000000,30341.000000,30390.000000,30475.0,30475.000000,30475.000000,22155.000000,30475
mean,1.273040e+07,90.738659,10584.830691,1.530141,1.0,12.019852,163.598950,91.993230,2013-06-29 17:56:15.317473024
min,5.000000e+02,20.000000,1003.000000,0.000000,1.0,0.000000,10.000000,20.000000,2008-06-26 00:00:00
25%,2.700193e+06,85.000000,10017.000000,1.000000,1.0,0.000000,80.000000,89.000000,2012-06-21 00:00:00
50%,8.551260e+06,90.000000,10065.000000,1.000000,1.0,3.000000,125.000000,94.000000,2013-09-01 00:00:00
75%,2.119605e+07,100.000000,11216.000000,2.000000,1.0,13.000000,195.000000,100.000000,2014-09-12 00:00:00
max,4.303307e+07,100.000000,99135.000000,16.000000,1.0,257.000000,10000.000000,100.000000,2015-08-31 00:00:00
std,1.190164e+07,9.059519,921.324686,1.015395,0.0,21.981496,197.792306,8.850373,NaN

In [43]:
df.duplicated().sum()

np.int64(17)

##Task 2

In [9]:
df.isnull().sum()

Host Id                          0
Host Since                       0
Name                             0
Neighbourhood                    0
Property Type                    3
Review Scores Rating (bin)    8320
Room Type                        0
Zipcode                        134
Beds                            85
Number of Records                0
Number Of Reviews                0
Price                            0
Review Scores Rating          8320
dtype: int64

###Review null handling

In [41]:
median_review_score_rating = df['Review Scores Rating'].median()
median_review_score_rating_bin = df['Review Scores Rating (bin)'].median()

df['Review Scores Rating'].fillna(median_review_score_rating, inplace=True)
df['Review Scores Rating (bin)'].fillna(median_review_score_rating_bin, inplace=True)

print(f"Missing values in 'Review Scores Rating' after imputation: {df['Review Scores Rating'].isnull().sum()}")
print(f"Missing values in 'Review Scores Rating (bin)' after imputation: {df['Review Scores Rating (bin)'].isnull().sum()}")

Missing values in 'Review Scores Rating' after imputation: 0
Missing values in 'Review Scores Rating (bin)' after imputation: 0

/tmp/ipykernel_1100/2697871350.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review Scores Rating'].fillna(median_review_score_rating, inplace=True)
/tmp/ipykernel_1100/2697871350.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review Scores Rating (bin)'].fillna(median_review_score_rating_bin, inplace=True)

In [42]:
df.isnull().sum()

Host Id                         0
Host Since                      0
Name                            0
Neighbourhood                   0
Property Type                   3
Review Scores Rating (bin)      0
Room Type                       0
Zipcode                       134
Beds                           85
Number of Records               0
Number Of Reviews               0
Price                           0
Review Scores Rating            0
Host Since_dt                   0
dtype: int64

In [ ]:
#The median is less affected by extreme low scores (outliers) that could skew the mean and misrepresent typical reviews.
#Review Scores Rating' values is crucial for building a price prediction model
#Keeping both columns for now, as they might offer different insights so we can investigate their correlation or impact on price to decide.

###Handle missing values

In [46]:
mode_property_type = df['Property Type'].mode()[0]
df['Property Type'].fillna(mode_property_type, inplace=True)

mode_zipcode = df['Zipcode'].mode()[0]
df['Zipcode'].fillna(mode_zipcode, inplace=True)

median_beds = df['Beds'].median()
df['Beds'].fillna(median_beds, inplace=True)

print("Missing values after imputation:")
display(df.isnull().sum())

Missing values after imputation:

/tmp/ipykernel_1100/3717887673.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Zipcode'].fillna(mode_zipcode, inplace=True)
/tmp/ipykernel_1100/3717887673.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Beds'].fillna(median_beds, inplace=True)

Host Id                       0
Host Since                    0
Name                          0
Neighbourhood                 0
Property Type                 0
Review Scores Rating (bin)    0
Room Type                     0
Zipcode                       0
Beds                          0
Number of Records             0
Number Of Reviews             0
Price                         0
Review Scores Rating          0
Host Since_dt                 0
dtype: int64

##Task 3

In [69]:
# new interaction feature
df['Neighbourhood_RoomType'] = df['Neighbourhood '] + '_' + df['Room Type']
display(df[['Neighbourhood ', 'Room Type', 'Neighbourhood_RoomType']].head())

  Neighbourhood         Room Type     Neighbourhood_RoomType
0      Manhattan  Entire home/apt  Manhattan_Entire home/apt
1      Manhattan     Private room     Manhattan_Private room
2       Brooklyn  Entire home/apt   Brooklyn_Entire home/apt
3      Manhattan  Entire home/apt  Manhattan_Entire home/apt
4       Brooklyn     Private room      Brooklyn_Private room

In [71]:
# Define the target variable
y = df['Price']

###Dataset without new features

In [72]:
# Drop columns
drop_cols_original = ['Host Id', 'Name', 'Number of Records', 'Price', 'Host Since', 'Host Since_dt']
features_original = [col for col in df.columns if col not in drop_cols_original and col != 'Neighbourhood_RoomType']

X_original = df[features_original].copy()

In [73]:
# One-hot encode categorical features
categorical_cols_original = ['Neighbourhood ', 'Property Type', 'Room Type', 'Zipcode']
X_original = pd.get_dummies(X_original, columns=categorical_cols_original, drop_first=True)

#### Dataset with the new feature

In [74]:
drop_cols_engineered = ['Host Id', 'Name', 'Number of Records', 'Price', 'Host Since', 'Host Since_dt']
features_engineered = [col for col in df.columns if col not in drop_cols_engineered]

X_engineered = df[features_engineered].copy()

In [75]:
# One-hot encode
categorical_cols_engineered = ['Neighbourhood ', 'Property Type', 'Room Type', 'Zipcode', 'Neighbourhood_RoomType']
X_engineered = pd.get_dummies(X_engineered, columns=categorical_cols_engineered, drop_first=True)


print("Shape of X_original:", X_original.shape)
print("Shape of X_engineered:", X_engineered.shape)

Shape of X_original: (30475, 215)
Shape of X_engineered: (30475, 229)

##Scaling

In [87]:
X_train_orig, X_test_orig, y_train_orig, y_test_orig = train_test_split(X_original, y, test_size=0.2, random_state=42)

# Initialize StandardScaler
scaler_orig = StandardScaler()

X_train_orig_scaled = scaler_orig.fit_transform(X_train_orig)
X_test_orig_scaled = scaler_orig.transform(X_test_orig)

In [92]:
X_train_eng, X_test_eng, y_train_eng, y_test_eng = train_test_split(X_engineered, y, test_size=0.2, random_state=42)

# Initialize StandardScaler
scaler_eng = StandardScaler()

X_train_eng_scaled = scaler_eng.fit_transform(X_train_eng)
X_test_eng_scaled = scaler_eng.transform(X_test_eng)

##train Random Forest Regressor

In [93]:
# Initialize and  for the SCALED original dataset
rf_model_orig_scaled = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_model_orig_scaled.fit(X_train_orig_scaled, y_train_orig)

y_pred_orig_scaled = rf_model_orig_scaled.predict(X_test_orig_scaled)

# Calculate RMSE
rmse_original_scaled = np.sqrt(mean_squared_error(y_test_orig, y_pred_orig_scaled))
print(f"RMSE for SCALED Original Dataset: {rmse_original_scaled:.4f}")

RMSE for SCALED Original Dataset: 163.6363

In [94]:
# Initialize and train SCALED engineered dataset
rf_model_eng_scaled = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_model_eng_scaled.fit(X_train_eng_scaled, y_train_eng)

y_pred_eng_scaled = rf_model_eng_scaled.predict(X_test_eng_scaled)

# Calculate RMSE
rmse_engineered_scaled = np.sqrt(mean_squared_error(y_test_eng, y_pred_eng_scaled))
print(f"RMSE for SCALED Engineered Dataset: {rmse_engineered_scaled:.4f}")

RMSE for SCALED Engineered Dataset: 163.3214

In [95]:
if rmse_engineered_scaled < rmse_original_scaled:
    print(f"With scaling, the engineered dataset performed better with RMSE: {rmse_engineered_scaled:.4f} compared to the scaled original dataset's RMSE: {rmse_original_scaled:.4f}")
elif rmse_engineered_scaled > rmse_original_scaled:
    print(f"With scaling, the original dataset performed better with RMSE: {rmse_original_scaled:.4f} compared to the scaled engineered dataset's RMSE: {rmse_engineered_scaled:.4f}")
else:
    print(f"With scaling, both datasets performed similarly with RMSE: {rmse_original_scaled:.4f}")

With scaling, the engineered dataset performed better with RMSE: 163.3214 compared to the scaled original dataset's RMSE: 163.6363

In [ ]:
#Yes, the Neighbourhood_RoomType interaction feature did improve the model's performance,
#resulting in a slightly lower RMSE 163.3214 vs 163.6363.

#It helped the model understand that a room's value isn't just about its neighborhood or type individually,
#but how those two factors combine in specific ways. This unique pairing offers a clearer picture for more accurate pricing.

##Task 4

In [ ]:
#Based on our previous analysis, the scaled engineered dataset had a slightly better RMSE.

In [96]:
rf_final_model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_final_model.fit(X_train_eng_scaled, y_train_eng)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [97]:
y_pred_final = rf_final_model.predict(X_test_eng_scaled)

In [99]:
# Calculate RMSE
rmse_final_model = np.sqrt(mean_squared_error(y_test_eng, y_pred_final))
print(f"\nFinal Model RMSE: {rmse_final_model:.4f}")

Final Model RMSE: 163.3214

In [ ]:
#The RMSE (Root Mean Squared Error) for your final model is 163.3214.

In [100]:
#This result indicates the model's average prediction error for the Airbnb prices using the features we engineered and scaled.
#A lower RMSE generally suggests a better-performing model
# The interaction feature contributed positively to this performance by capturing more relationships in the data

In [ ]:
#For very high-priced listings, this might be a small percentage error, but for lower-priced listings, it could represent a larger proportion of the price.

##Task 5

In [108]:
import joblib
model_filename = 'airbnb_rf_model.joblib'
scaler_filename = 'airbnb_scaler.joblib'
columns_filename = 'airbnb_training_columns.joblib' # New: Filename for training columns

joblib.dump(rf_final_model, model_filename)
print(f"Trained model saved as '{model_filename}'")

joblib.dump(scaler_eng, scaler_filename)
print(f"Scaler saved as '{scaler_filename}'")

# Save the training columns (feature names) as well
joblib.dump(X_engineered.columns.tolist(), columns_filename)
print(f"Training columns saved as '{columns_filename}'")

Trained model saved as 'airbnb_rf_model.joblib'
Scaler saved as 'airbnb_scaler.joblib'
Training columns saved as 'airbnb_training_columns.joblib'

##app.py

In [109]:
%%writefile app.py

import joblib
import pandas as pd
from flask import Flask, request, jsonify, render_template
import numpy as np # Import numpy for numerical operations

app = Flask(__name__)

# Define model, scaler, and columns filenames
model_filename = 'airbnb_rf_model.joblib'
scaler_filename = 'airbnb_scaler.joblib'
columns_filename = 'airbnb_training_columns.joblib' # New: Filename for training columns

# Load the trained model, scaler, and training columns
try:
    model = joblib.load(model_filename)
    scaler = joblib.load(scaler_filename)
    TRAINING_COLUMNS = joblib.load(columns_filename) # New: Load training columns
    print(f"Model '{model_filename}', Scaler '{scaler_filename}', and Training Columns '{columns_filename}' loaded successfully.")
except FileNotFoundError:
    print(f"Error: One or more files not found. Please ensure '{model_filename}', '{scaler_filename}', and '{columns_filename}' are in the same directory.")
    model = None # Set to None to handle errors later
    scaler = None
    TRAINING_COLUMNS = [] # Initialize as empty list to prevent NameError

@app.route('/')
def index():
    return render_template('index.html')


@app.route('/predict', methods=['POST'])
def predict():
    if model is None or scaler is None:
        return jsonify({'error': 'Model or scaler not loaded. Check server logs.'}), 500

    try:
        data = request.get_json(force=True)

        # Convert input JSON data to DataFrame
        input_df = pd.DataFrame([data])

        # Preprocessing

        # 1. Feature Engineering
        if 'Neighbourhood ' in input_df.columns and 'Room Type' in input_df.columns:
            input_df['Neighbourhood_RoomType'] = input_df['Neighbourhood '] + '_' + input_df['Room Type']
        else:
            # This case should ideally not happen if the frontend sends all required inputs
            # For robustness, we can try to proceed without the interaction feature if inputs are truly missing,
            # but it's better to ensure the frontend sends all necessary data.
            # For now, let's raise an error to indicate missing input.
            return jsonify({'error': 'Missing Neighbourhood or Room Type for interaction feature.'}), 400

        # 2. One-hot encode
        # Ensure all expected categorical columns are present in input_df, even if with NaN, before one-hot encoding.
        # This is important if some categories might be missing in a single prediction request.
        categorical_features_for_ohe = ['Neighbourhood ', 'Property Type', 'Room Type', 'Zipcode', 'Neighbourhood_RoomType']

        for col in categorical_features_for_ohe:
            if col not in input_df.columns:
                input_df[col] = np.nan # Add missing categorical column with NaN to be handled by get_dummies

        input_df_encoded = pd.get_dummies(input_df, columns=categorical_features_for_ohe, drop_first=True)

        # Add missing columns (features that were in training data but not in this specific input)
        missing_cols = set(TRAINING_COLUMNS) - set(input_df_encoded.columns)
        for c in missing_cols:
            input_df_encoded[c] = 0

        # Drop any extra columns (features that were in this specific input but not in training data)
        extra_cols = set(input_df_encoded.columns) - set(TRAINING_COLUMNS)
        input_df_encoded = input_df_encoded.drop(columns=list(extra_cols))

        # Reorder columns to match the training set
        final_input = input_df_encoded[TRAINING_COLUMNS]

        # 3. Scale numerical features
        final_input_scaled = scaler.transform(final_input)

        # Make prediction
        prediction = model.predict(final_input_scaled)
        predicted_price = round(prediction[0], 2)

        # Calculate a plausible price range (e.g., +/- 10% of the predicted price)
        range_percentage = 0.10 # 10%
        lower_bound = round(predicted_price * (1 - range_percentage), 2)
        upper_bound = round(predicted_price * (1 + range_percentage), 2)

        return jsonify({
            'predicted_price': predicted_price,
            'price_range_lower': lower_bound,
            'price_range_upper': upper_bound
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 400

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)

Overwriting app.py